dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otelcorecol
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.102.0-dev
  otelcol_version: 0.102.0

conf_resolver:
  default_uri_scheme: "env"

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.102.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.102.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.102.0
extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.102.0
  - gomod: go.opentelemetry.io/collector/extension/memorylimiterextension v0.102.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.102.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.102.0
connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.102.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v0.102.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v0.102.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v0.102.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.102.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.102.0

