# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: deprecation

# The name of the component, or a single word describing the area of concern, (e.g. otlpreceiver)
component: service

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Deprecate service.PipelineConfig in favor of pipelines.Config.

# One or more tracking issues or pull requests related to the change
issues: [7854]

